Обратная связь и оптимизация
htmlacademy-javascript/2324921-kekstagram-1 pull request #11
Opened 2024-09-16 12:58 UTC by baranovdmitriy87

2024-09-16 21:25 UTC, baranovdmitriy87 commented
У последнего коммита сделал поправку в коде. Закомментировал модуль(choose-picture) с выбором картинок из папки и загрузкой в форму, согласно 3-му заданию Д/З. Немного забежал вперед, поэтому модуль и закомментировал, тк это должно быть сделано для module12-task2

2024-09-17 16:57 UTC, wonderjs requested changes
Отлично, давай в качестве доп задания добавим замену картинок также и на карточках эффектов, чтобы вместо дефолтного котика, была загруженная пользователем картинка.

2024-09-17 16:57 UTC, wonderjs commented on js/util.js
> +function throttle(callback, delayBetweenFrames) {
если функция в итоге не пригодилась, то не убираем ее

2024-09-17 16:57 UTC, wonderjs commented on js/main.js
> +  renderGallery(getFilteredPictures);
Здесь просто нужно передать data и ошибки не будет =) Либо вызвать getFilteredPictures, ведь это функция

2024-09-18 19:48 UTC, wonderjs approved these changes

2024-09-18 19:48 UTC, merged