Открывается и закрывается
htmlacademy-javascript/2324921-kekstagram-1 pull request #6
Opened 2024-08-02 11:06 UTC by baranovdmitriy87

2024-08-02 12:12 UTC, wonderjs requested changes
Не забывать про линтер! проверить ошибки, причесать код, убрать/закомментаривать код из следующей домашки по комментариям

2024-08-02 12:12 UTC, wonderjs commented on js/big-picture.js
> +const COMMENTS_PER_PORTION = 5  /** Возможно эту перем. вынести в файл const.js и импортировать в этот модуль*/
Константа здесь должна быть, всё ок. Но забыл точку с запятой в конце. Ты проверял код линтером перед комитом?

2024-08-02 12:12 UTC, wonderjs commented on js/big-picture.js
> +const commentCount = document.querySelector('.social__comment-count');
DOM-элементы, которые находятся внутри bigPicture можно искать уже не по всему document, а внутри bitPicture

2024-08-02 12:12 UTC, wonderjs commented on js/big-picture.js
> +  const comment = document.createElement('li');
Можно завести template в index.html для одного комментария, тогда здесь будешь просто клонировать его и заполнять данными

2024-08-02 12:12 UTC, wonderjs commented on js/big-picture.js
> +  commentCount.innerHTML = '${commentsShown}'; /** Добавить еще...но не совсем пойму что конкретно и для чего  */
Этот блок нам в этой домашке пока не нужен, он скрыт

2024-08-02 12:12 UTC, wonderjs commented on js/big-picture.js
> +  showBigPicture();
Почему на кнопку закрыть мы вызываем функцию открытия? Должна быть функция закрытия, не вижу ее вообще

2024-08-02 12:12 UTC, wonderjs commented on js/big-picture.js
> +  bigPicture.querySelector('social__caption').textContent = description;
Все эти DOM-элементы постоянно присутствуют в разметке, их не нужно искать каждый раз при вызове функции, вынеси их в переменные наверх, здесь только заполняем данные

2024-08-02 12:12 UTC, wonderjs commented on js/big-picture.js
> +  document.addEventListener('keydown', onDocumentKeydown);
Забыл определить функцию onDocumentKeydown

2024-08-02 12:12 UTC, wonderjs commented on js/mocks/const.js
> +// const COMMENTS_PER_PORTION = 5;
убрать

2024-08-02 12:12 UTC, wonderjs commented on js/mocks/const.js
> +export { NAMES, PICTURE_COUNT, AVATAR_COUNT, LIKE_MIN_COUNT, LIKE_MAX_COUNT, COMMENT_COUNT, COMMENTS_STROKES, DESCRIPTIONS, COMMENTS_PER_PORTION };
убрать экспорт COMMENTS_PER_PORTION

2024-08-02 12:12 UTC, wonderjs commented on js/thumbnail.js
> +  const randomPicture = thumbnail.querySelector('.picture__img');
лучше переименовать просто в picture или image, оно же не рандомное =)

2024-08-02 12:12 UTC, wonderjs commented on js/big-picture.js
> +let commentsShown = 0;
В этой домашке нам нужно отрендерить все комментарии, в следующей уже будем их рисовать порциями по 5 штук при нажатии на кнопку загрузить ещё, не торопись

2024-08-02 12:20 UTC, baranovdmitriy87 commented on js/big-picture.js
> +const COMMENTS_PER_PORTION = 5  /** Возможно эту перем. вынести в файл const.js и импортировать в этот модуль*/
Проверял, но после коммита(

2024-08-02 12:46 UTC, baranovdmitriy87 commented on js/big-picture.js
> +  const comment = document.createElement('li');
Не совсем понял, как это реализовать

2024-08-05 11:23 UTC, wonderjs requested changes

2024-08-05 11:23 UTC, wonderjs commented on js/gallery.js
> +import { renderThumbnails } from './thumbnail';
забыл указать расширение файла .js

2024-08-06 07:22 UTC, wonderjs requested changes

2024-08-06 07:22 UTC, wonderjs commented on js/big-picture.js
> +  renderComments(data.comments);
Что-то ты удалил больше кода, чем было нужно. В этом задании нам нужно отрендерить все комментарии по фотографии и временно скрыть счетчик комментариев и кнопку Загрузить ещё. Тк функционал подгрузки по 5 комментариев мы будем делать в следующем задании.
Осталось сделать:
- Список комментариев под фотографией: комментарии должны вставляться в блок .social__comments. 
- После открытия окна спрячьте блоки счётчика комментариев .social__comment-count и загрузки новых комментариев .comments-loader, добавив им класс hidden, с ними мы разберёмся позже, в другом домашнем задании.

2024-08-07 05:55 UTC, merged